In [180]:
import datetime
import pandas as pd
import re
from itertools import permutations

print (f'{datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')

2020-12-04 19:06:52

**--- Day 4: Passport Processing ---**

You arrive at the airport only to realize that you grabbed your North Pole Credentials instead of your passport. While these documents are extremely similar, North Pole Credentials aren't issued by a country and therefore aren't actually valid documentation for travel in most of the world.

It seems like you're not the only one having problems, though; a very long line has formed for the automatic passport scanners, and the delay could upset your travel itinerary.

Due to some questionable network security, you realize you might be able to solve both of these problems at the same time.

The automatic passport scanners are slow because they're having trouble detecting which passports have all required fields. The expected fields are as follows:

byr (Birth Year)
iyr (Issue Year)
eyr (Expiration Year)
hgt (Height)
hcl (Hair Color)
ecl (Eye Color)
pid (Passport ID)
cid (Country ID)
Passport data is validated in batch files (your puzzle input). Each passport is represented as a sequence of key:value pairs separated by spaces or newlines. Passports are separated by blank lines.

Here is an example batch file containing four passports:

ecl:gry pid:860033327 eyr:2020 hcl:#fffffd
byr:1937 iyr:2017 cid:147 hgt:183cm

iyr:2013 ecl:amb cid:350 eyr:2023 pid:028048884
hcl:#cfa07d byr:1929

hcl:#ae17e1 iyr:2013
eyr:2024
ecl:brn pid:760753108 byr:1931
hgt:179cm

hcl:#cfa07d eyr:2025 pid:166559648
iyr:2011 ecl:brn hgt:59in

The first passport is valid - all eight fields are present. The second passport is invalid - it is missing hgt (the Height field).

The third passport is interesting; the only missing field is cid, so it looks like data from North Pole Credentials, not a passport at all! Surely, nobody would mind if you made the system temporarily ignore missing cid fields. Treat this "passport" as valid.

The fourth passport is missing two fields, cid and byr. Missing cid is fine, but missing any other field is not, so this passport is invalid.

According to the above rules, your improved system would report 2 valid passports.

Count the number of valid passports - those that have all required fields. Treat cid as optional. In your batch file, how many passports are valid?

In [185]:
f = open('../data/data4.tsv')
lines = f.readlines()
df = pd.DataFrame(' '.join(lines).replace('\n', '').replace('  ', '\n').split('\n'), columns=['id'])

df['byr'] = df['id'].str.split('byr:').str[1].str.split(' ').str[0]
df['iyr'] = df['id'].str.split('iyr:').str[1].str.split(' ').str[0]
df['eyr'] = df['id'].str.split('eyr:').str[1].str.split(' ').str[0]
df['hgt'] = df['id'].str.split('hgt:').str[1].str.split(' ').str[0]
df['hcl'] = df['id'].str.split('hcl:').str[1].str.split(' ').str[0]
df['ecl'] = df['id'].str.split('ecl:').str[1].str.split(' ').str[0]
df['pid'] = df['id'].str.split('pid:').str[1].str.split(' ').str[0]
df['cid'] = df['id'].str.split('cid:').str[1].str.split(' ').str[0]

df = df.loc[~df['byr'].isnull()]
df = df.loc[~df['iyr'].isnull()]
df = df.loc[~df['eyr'].isnull()]
df = df.loc[~df['hgt'].isnull()]
df = df.loc[df['hgt'] != 'nan']
df = df.loc[~df['hcl'].isnull()]
df = df.loc[(df['hcl'] != 'nan')]
df = df.loc[~df['ecl'].isnull()]
df = df.loc[(df['ecl'] != 'nan')]
df = df.loc[~df['pid'].isnull()]
df = df.loc[(df['pid'] != 'nan')]

df = df.loc[df['byr'].str.contains('(\d){4}')]
df = df.loc[df['iyr'].str.contains('(\d){4}')]
df = df.loc[df['eyr'].str.contains('(\d){4}')]
df['byr'] = df['byr'].astype(int)
df['iyr'] = df['iyr'].astype(int)
df['eyr'] = df['eyr'].astype(int)
df = df.loc[(df['byr'] >= 1920)&(df['byr'] <= 2003)]
df = df.loc[(df['iyr'] >= 2010)&(df['iyr'] <= 2020)]
df = df.loc[(df['eyr'] >= 2020)&(df['eyr'] <= 2030)]

df = df.loc[df['hgt'].str.contains('^(\d)+(in|cm)$')]
df = df.loc[df['hcl'].str.contains(r'^#([0-9]*|[a-f]*){6}$')]
df = df.loc[df['ecl'].str.contains(r'|'.join(['amb', 'blu', 'brn', 'gry', 'grn', 'hzl', 'oth']))]
df = df.loc[df['pid'].str.contains(r'^(\d){9}$')]

def check_hgt(height):
    if not re.match('^(\d)+(in|cm)$', height):
        return False
    m = int(height[:-2])
    if height.endswith('in'):
        return 59 <= m <= 76
    else:
        return 150 <= m <= 193

df['check_hgt'] = [check_hgt(hgt) for hgt in df['hgt']]

/local/fpozoc/miniconda3/envs/trifid/lib/python3.7/site-packages/pandas/core/strings.py:1954: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

byr (Birth Year)

iyr (Issue Year)

eyr (Expiration Year)

hgt (Height)

hcl (Hair Color)

ecl (Eye Color)

pid (Passport ID)

cid (Country ID) - optional -

In [187]:
df[df['check_hgt'] == True]

,id,byr,iyr,eyr,hgt,hcl,ecl,pid,cid,check_hgt
4,pid:472686027 ecl:oth iyr:2019 cid:277 byr:194...,1940,2019,2030,170cm,#62e117,oth,472686027,277,True
5,ecl:oth iyr:2017 pid:938461813 hcl:#733820 byr...,1959,2017,2022,159cm,#733820,oth,938461813,NaN,True
10,iyr:2020 eyr:2020 hcl:#18171d ecl:gry pid:9141...,2002,2020,2020,168cm,#18171d,gry,914128753,NaN,True
13,pid:762423097 iyr:2014 hcl:#a97842 ecl:brn hgt...,1927,2014,2021,180cm,#a97842,brn,762423097,NaN,True
15,eyr:2022 ecl:brn byr:1986 hgt:161cm cid:99 pid...,1986,2019,2022,161cm,#6b5442,brn,288726584,99,True
...,...,...,...,...,...,...,...,...,...,...
246,hgt:193cm pid:750729809 ecl:oth cid:324 iyr:20...,1954,2011,2020,193cm,#efcc98,oth,750729809,324,True
249,hgt:172cm ecl:hzl pid:839804598 hcl:#341e13 ey...,1964,2013,2030,172cm,#341e13,hzl,839804598,NaN,True
250,iyr:2018 hgt:152cm byr:1948 hcl:#623a2f pid:40...,1948,2018,2020,152cm,#623a2f,blu,400121515,NaN,True
253,cid:247 ecl:grn iyr:2014 hgt:178cm byr:1992 hc...,1992,2014,2021,178cm,#602927,grn,678964478,247,True
254,iyr:2010 pid:623705680 ecl:hzl hgt:181cm byr:1...,1980,2010,2028,181cm,#341e13,hzl,623705680,NaN,True